name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release'
        required: true
        default: 'v0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Create Git tag
        id: create_tag
        run: |
          echo "Creating tag ${GITHUB_EVENT_INPUTS_version}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release and upload binary
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Create the release using the GitHub API
          RELEASE_URL=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"tag_name": "'"$VERSION"'","name": "'"$VERSION"'","body": "Release for version '"$VERSION"'"}' \
            https://api.github.com/repos/${{ github.repository }}/releases)
          
          UPLOAD_URL=$(echo $RELEASE_URL | jq -r .upload_url | sed -e 's/{?name,label}//')

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @bin/app \
            "${UPLOAD_URL}?name=spotify-terminal-x86-linux-${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
